version: "3.6"

services:
  fcrepo:
    image: cbeer/fcrepo4:4.7
    ports:
      - 8080:8080
    volumes:
      - fcrepo_data:/data
    environment:
      - JAVA_OPTS=-Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
      # - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"

  db:
    image: mysql:5.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  redis:
    image: redis:4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores/californica/data
    ports:
      - "8983:8983"

  ursus:
    build:
      context: .
    depends_on:
      - solr
    ports:
      - "3003:3000"
    volumes:
      - ./ursus:/ursus
      - ./.git/modules/ursus:/.git/modules/ursus
      - ursus_bundle_dir:/usr/local/bundle
    working_dir: /ursus
    environment:
      DATABASE_NAME: ursus_development
      DATABASE_HOST: db
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      SOLR_URL: http://solr:8983/solr/californica
    command: "bundle exec rails server"

  californica:
    build:
      context: .
    command: "bundle exec rails server"
    depends_on:
      - db
      - fcrepo
      - redis
      - sidekiq
      - solr
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: californica
      DATABASE_USERNAME: californica
      FEDORA_URL: http://fcrepo:8080/fcrepo/rest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr:8983/solr/californica
    ports:
      - "3000:3000"
    volumes:
      - ./californica:/californica
      - californica_bundle_dir:/usr/local/bundle
    working_dir: /californica

  sidekiq:
    build:
      context: .
    command: "bundle exec sidekiq"
    depends_on:
      - db
      - fcrepo
      - redis
      - solr
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: californica
      DATABASE_USERNAME: californica
      FEDORA_URL: http://fcrepo:8080/fcrepo/rest
      GEONAMES_USERNAME: ""
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr:8983/solr/californica
    volumes:
      - ./californica:/californica
      - californica_bundle_dir:/usr/local/bundle
    working_dir: /californica

volumes:
  mysql_data:
  solr_data:
  redis_data:
  fcrepo_data:
  ursus_bundle_dir:
  californica_bundle_dir:
